site_name: SEEREP Documentation
repo_url: https://github.com/agri-gaia/seerep
docs_dir: docs/mkdocs
nav:
  - Home: 'home/index.md'
  - Getting started:
    - Dev Environment: 'getting-started/installationDev.md'
    - Kubernetes Deployment: 'getting-started/kubernetes-deployment.md'
    - Local Deployment: 'getting-started/local-deployment.md'
    - Docs: 'getting-started/docs.md'
    - Tests: 'getting-started/tests.md'
  - Reference:
    - Package Overview: 'reference/packages.md'
  - Tutorials:
    - Overview: 'tutorials/overview.md'
    - Creating & retrieving projects: 'tutorials/projects.md'
    - Sending & Querying Images: 'tutorials/images.md'
theme:
  name: material
  language: en
  theme:
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.sections
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
copyright: >
        <a href="/seerep/mkdocs/legal-notice/index.html">Legal Notice</a> - <a href="/seerep/mkdocs/data-protection-notice/index.html">Data Protection Notice</a>
