apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: seerep

resources:
  - persistent_volume.yaml
  - persistent_volume_claim.yaml
  - ca-secret-sealed.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
patches:
  - target:
      kind: SealedSecret
      name: seerep-ca
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: seerep
      - op: replace
        path: /spec/template/metadata/namespace
        value: seerep


configurations:
  - configuration/sealed-secret-config.yaml

configMapGenerator:
  - name:  seerep-cfg
    files:
      - seerep.cfg

secretGenerator:
  - name: ca-secret.yaml
    type: Opaque
