version: "3.9"
services:
  seerep:
    image: ghcr.io/agri-gaia/seerep_server:latest
    tty: true
    container_name: seerep_server
    command:
      # define data-dir for seerep-server
      - "--data-folder=/mnt/seerep-data"
    ports:
      # the gRPC port
      - 9090
    volumes:
      # persist the data folder
      - seerep-data:/mnt/seerep-data
volumes:
  seerep-data:
