apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: seerep-prod

resources:
  - ./../../base
patches:
  - target:
      kind: PersistentVolume
    patch: |-
      - op: replace
        path: /spec/hostPath/path
        value: /media/data/seerep-prod
  - target:
      kind: Ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: seerep-prod.robot.10.249.3.13.nip.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: seerep-prod.robot.10.249.3.13.nip.io

namePrefix: prod-

images:
  - name: seerep-server
    newTag: v1
