apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./../../base
patches:
  - target:
      kind: PersistentVolume
    patch: |-
      - op: replace
        path: /spec/hostPath/path
        value: /media/data/seerep-prod

namePrefix: prod-

images:
  - name: seerep-server
    newTag: v1
